package com.example.GSVessel.Model.Enums;

public enum EquipmentCategory {PROPULSION, ENERGIA, HIDRAULICA, TRATAMIENTO_AGUA, CUBIERTA,
    ILUMINACION, SEGURIDAD, CONFORT, CARGA, CORROSION,
    INSTRUMENTACION, AMORTIGUACION, RECUPERACION_ENERGIA
}
